import os
from pathlib import Path
import pathspec

# Default directories and files to always ignore to save tokens
DEFAULT_IGNORES = [
    '.git', '.svn', '.hg',

    'node_modules',
    'venv',
    'env',
    '.env',

    '__pycache__',
    '.pytest_cache',

    'package-lock.json',
    'yarn.lock',
    'pnpm-lock.yaml',

    # Generated by repo2llm itself
    'repo_prompt.txt'
]
BINARY_EXTENSIONS = {
    ".png",
    ".jpg",
    ".jpeg",
    ".gif",
    ".webp",

    ".pdf",
    ".zip",
    ".rar",
    ".7z",

    ".exe",
    ".dll",

    ".mp4",
    ".mp3",
}
MAX_FILE_SIZE = 1_000_000
def is_binary(file_path: Path) -> bool:

    if file_path.suffix.lower() in BINARY_EXTENSIONS:
        return True

    try:
        with open(file_path, 'rb') as f:
            chunk = f.read(1024)

            return b'\0' in chunk

    except Exception:
        return True

def get_gitignore_spec(root_dir: Path) -> pathspec.PathSpec:
    """
    Reads the .gitignore file and returns a pathspec object for filtering.
    """
    gitignore_path = root_dir / '.gitignore'
    lines = []
    
    if gitignore_path.exists():
        # ADDED: errors='ignore' prevents crashes if the .gitignore has weird characters
        with open(gitignore_path, 'r', encoding='utf-8', errors='ignore') as f:
            lines = f.readlines()
            
    # Add our default ignores to the spec
    lines.extend(DEFAULT_IGNORES)
    
    return pathspec.PathSpec.from_lines(pathspec.patterns.GitWildMatchPattern, lines)


def crawl_repository(root_dir: str) -> list[Path]:
    """
    Walks the repository, yielding file paths that are NOT ignored and NOT binary.
    """
    root_path = Path(root_dir).resolve()
    ignore_spec = get_gitignore_spec(root_path)
    
    valid_files = []
    
    for current_dir, dirs, files in os.walk(root_path):
        current_path = Path(current_dir)
        
        # Calculate the relative path from the root for .gitignore matching
        rel_dir = current_path.relative_to(root_path)
        
        # FIX 1: Add a trailing slash for directories and force POSIX format (forward slashes)
        dirs[:] = [
            d for d in dirs 
            if not ignore_spec.match_file(f"{(rel_dir / d).as_posix()}/")
        ]
        
        for file in files:
            file_path = current_path / file
            rel_file_path = file_path.relative_to(root_path)
            
            # FIX 2: Force POSIX format for files so Windows backslashes don't break the regex
            if ignore_spec.match_file(rel_file_path.as_posix()):
                continue
                
            # Skip huge files
            if file_path.stat().st_size > MAX_FILE_SIZE:
                continue

            # Skip binary files
            if is_binary(file_path):
                continue

            valid_files.append(file_path)
            
    return valid_files

# --- Quick Test ---
if __name__ == "__main__":
    # Run this file directly to test the crawler on its own directory
    test_dir = "."
    print(f"Crawling {test_dir}...")
    files = crawl_repository(test_dir)
    for f in files:
        print(f.relative_to(Path(test_dir).resolve()))